---
title: "Final Draft"
author: "Lucy Ding"
date: "5/2/2022"
output: html_document
---

# Loading Packages

```{r, warning = FALSE}
library(tidyverse)
library(janitor)
library(readxl)
library(usmap)
library(stargazer)
library(haven)
library(tigris)
library(rio)
library(standardize)
library(effsize)
library(ggthemes)
```

# Load Datasets

```{r, output = FALSE, warning = FALSE}
df_immi <- read_excel("migration_df.xls")
df_emi <- read_excel("migration_df2.xls")
```

# Immigration

```{r, output = FALSE, warning = FALSE}
# Basic linear regression
stargazer(lm(dem_prop ~ avg_immi_rate, data = df_immi, weight = total_pop),
          type = "text")
```

```{r, warning = FALSE, message = FALSE}
# Visualization of relationship between immigration rate and dem percent
ggplot(df_immi, aes(x = avg_immi_rate, y = dem_prop, size = total_pop)) +
  geom_point(alpha = .3) +
  geom_smooth(method = "lm", aes(weight = total_pop), show.legend = FALSE) +
  labs(title = "Fall in Democratic Voting with Increase in Rate of Immigration",
       x = "Immigration Rate",
       y = "Two-Party Democratic Vote Share",
       subtitle = "2020 Presidential Election",
       caption = "Weighted by County Population")
```

```{r, warning = FALSE, message = FALSE}
# Regression with controls
stargazer(lm(dem_prop ~ avg_immi_rate + percent_white + percent_hispanic +
               percent_bachelors + avg_wage + poverty + unemp + med_household_income, data = df_immi,
             weight = total_pop),
          lm(dem_prop ~ avg_immi_rate + percent_white + percent_hispanic +
               percent_bachelors, data = df_immi,
             weight = total_pop),
          lm(dem_prop ~ avg_immi_rate + avg_wage + poverty + unemp + med_household_income, data = df_immi,
             weight = total_pop),
          type = "text")
```

```{r, warning = FALSE, message = FALSE}
# Regression standardized
df_immi$dem_prop_scaled <- scale(df_immi$dem_prop)[, 1]
df_immi$avg_immi_rate_scaled <- scale(df_immi$avg_immi_rate)[, 1]
df_immi$percent_white_scaled <- scale(df_immi$percent_white)[, 1]
df_immi$percent_bachelors_scaled <- scale(df_immi$percent_bachelors)[, 1]
df_immi$med_household_income_scaled <- scale(df_immi$med_household_income)[, 1]
df_immi$percent_hispanic_scaled <- scale(df_immi$percent_hispanic)[, 1]
df_immi$avg_wage_scaled <- scale(df_immi$avg_wage)[, 1]
df_immi$poverty_scaled <- scale(df_immi$poverty)[, 1]
df_immi$unemp_scaled <- scale(df_immi$unemp)[, 1]

stargazer(lm(dem_prop_scaled ~ avg_immi_rate_scaled + percent_white_scaled + percent_bachelors_scaled + 
               med_household_income_scaled + percent_hispanic_scaled +
               avg_wage_scaled + poverty_scaled + unemp_scaled, data = df_immi,
          weight = total_pop), type = "text")
```


# Emigration

```{r, output = FALSE, warning = FALSE}
# Basic linear regression
stargazer(lm(dem_prop ~ avg_emi_rate, data = df_emi, weight = total_pop),
          type = "text")
```

```{r, warning = FALSE, message = FALSE}
# Visualization of relationship between immigration rate and dem percent
ggplot(df_emi, aes(x = avg_emi_rate, y = dem_prop, size = total_pop)) +
  geom_point(alpha = .3) +
  geom_smooth(method = "lm", aes(weight = total_pop), show.legend = FALSE) +
  labs(title = "Fall in Democratic Voting with Increase in Rate of Immigration",
       x = "Immigration Rate",
       y = "Two-Party Democratic Vote Share",
       subtitle = "2020 Presidential Election",
       caption = "Weighted by County Population")
```

```{r, warning = FALSE, message = FALSE}
# Regression with controls
stargazer(lm(dem_prop ~ avg_emi_rate + percent_white + percent_hispanic +
               percent_bachelors + avg_wage + poverty + unemp + med_household_income, data = df_emi,
             weight = total_pop),
          lm(dem_prop ~ avg_emi_rate + percent_white + percent_hispanic +
               percent_bachelors, data = df_emi,
             weight = total_pop),
          lm(dem_prop ~ avg_emi_rate + avg_wage + poverty + unemp + med_household_income, data = df_emi,
             weight = total_pop),
          type = "text")
```

```{r, warning = FALSE, message = FALSE}
# Regression standardized
df_emi$dem_prop_scaled <- scale(df_emi$dem_prop)[, 1]
df_emi$avg_emi_rate_scaled <- scale(df_emi$avg_emi_rate)[, 1]
df_emi$percent_white_scaled <- scale(df_emi$percent_white)[, 1]
df_emi$percent_bachelors_scaled <- scale(df_emi$percent_bachelors)[, 1]
df_emi$med_household_income_scaled <- scale(df_emi$med_household_income)[, 1]
df_emi$percent_hispanic_scaled <- scale(df_emi$percent_hispanic)[, 1]
df_emi$avg_wage_scaled <- scale(df_emi$avg_wage)[, 1]
df_emi$poverty_scaled <- scale(df_emi$poverty)[, 1]
df_emi$unemp_scaled <- scale(df_emi$unemp)[, 1]

stargazer(lm(dem_prop_scaled ~ avg_emi_rate_scaled + percent_white_scaled + percent_bachelors_scaled + 
               med_household_income_scaled + percent_hispanic_scaled +
               avg_wage_scaled + poverty_scaled + unemp_scaled, data = df_emi,
          weight = total_pop), type = "text")
```

